language: go

go:
  - 1.10.x
  - tip

before_install:
  - go get -t -v ./...

script:
  - bash .test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 8e3bc1da-7388-438a-a03b-45b87d45c20c
